### ISSUE TITLE
list-config fails

### ISSUE THREAD

**Issue by djdeath** [intel/vaapi-fits#19]
```
$ ./vaapi-fits list-config
Extracting assets...
Traceback (most recent call last):
  File "./vaapi-fits", line 20, in <module>
    sys.exit(main())
  File "./vaapi-fits", line 17, in main
    return main_entry_point()
  File "/home/djdeath/.local/lib/python2.7/site-packages/slash/frontend/main.py", line 71, in main_entry_point
    sys.exit(main())
  File "/home/djdeath/.local/lib/python2.7/site-packages/slash/frontend/main.py", line 47, in main
    returned = func(args.argv)
  File "/home/djdeath/.local/lib/python2.7/site-packages/slash/frontend/list_config.py", line 29, in list_config
    slash.site.load()
  File "/home/djdeath/.local/lib/python2.7/site-packages/slash/site.py", line 17, in load
    return _load_defaults(working_directory=working_directory)
  File "/home/djdeath/.local/lib/python2.7/site-packages/slash/site.py", line 22, in _load_defaults
    _load_local_slashrc(working_directory=working_directory)
  File "/home/djdeath/.local/lib/python2.7/site-packages/slash/site.py", line 37, in _load_local_slashrc
    _load_file_if_exists(os.path.abspath(path))
  File "/home/djdeath/.local/lib/python2.7/site-packages/slash/site.py", line 44, in _load_file_if_exists
    _load_filename(path)
  File "/home/djdeath/.local/lib/python2.7/site-packages/slash/site.py", line 67, in _load_filename
    _load_source(f.read(), filename)
  File "/home/djdeath/.local/lib/python2.7/site-packages/slash/site.py", line 76, in _load_source
    exec(code, {"__file__" : filename}) # pylint: disable=W0122
  File "/home/djdeath/src/mesa-src/vaapi-fits/.slashrc", line 276, in <module>
    execfile(config)
  File "/home/djdeath/src/mesa-src/vaapi-fits/config/default", line 14, in <module>
    with tarfile.open("{}.tbz2".format(assets), "r:*") as tf:
  File "/usr/lib/python2.7/tarfile.py", line 1680, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```

**Comment by djdeath** [comment]
I think I just missed running `git lfs pull`

**Comment by uartie** [comment]
Yes, we should provide a more user-friendly error message.
